# Generated by Django 3.0.1 on 2020-07-17 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('level', models.CharField(default='no level', max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
